/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.Customer;
import models.Order;

/**
 *
 * @author 30397446
 */
public class CustomerHome extends javax.swing.JFrame {

    private Customer loggedInCustomer;
    private Order currentOrder;
    /**
     * Creates new form CustomerHome
     */
    public CustomerHome(Customer customer, Order currentOrder) {
        loggedInCustomer = customer;
        this.currentOrder = currentOrder;
        initComponents();
        
        
        lblGreeting.setText(loggedInCustomer.displayGreeting());
    }

    CustomerHome(Customer customer) {
        loggedInCustomer = customer;
        this.currentOrder = new Order();
        initComponents();
        
        
        lblGreeting.setText(loggedInCustomer.displayGreeting());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerHome = new javax.swing.JLabel();
        btnCstBrowseProducts = new javax.swing.JButton();
        btnCstViewMyProducts = new javax.swing.JButton();
        btnCstEditDetails = new javax.swing.JButton();
        btnCstUnregisterFromShop = new javax.swing.JButton();
        btnCstLogOut = new javax.swing.JButton();
        lblGreeting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCustomerHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCustomerHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerHome.setText("CUSTOMER HOME");

        btnCstBrowseProducts.setText("Browse Products");
        btnCstBrowseProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCstBrowseProductsActionPerformed(evt);
            }
        });

        btnCstViewMyProducts.setText("View My Orders");
        btnCstViewMyProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCstViewMyProductsActionPerformed(evt);
            }
        });

        btnCstEditDetails.setText("Edit Details");

        btnCstUnregisterFromShop.setText("Unregister from shop");

        btnCstLogOut.setText("Log Out");
        btnCstLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCstLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCstLogOut)
                    .addComponent(btnCstUnregisterFromShop)
                    .addComponent(btnCstEditDetails)
                    .addComponent(btnCstViewMyProducts)
                    .addComponent(btnCstBrowseProducts)
                    .addComponent(lblCustomerHome))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblCustomerHome)
                .addGap(18, 18, 18)
                .addComponent(btnCstBrowseProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCstViewMyProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCstEditDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCstUnregisterFromShop)
                .addGap(36, 36, 36)
                .addComponent(btnCstLogOut)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCstLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCstLogOutActionPerformed
        CustomerLogin customerLogin = new CustomerLogin();
        customerLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCstLogOutActionPerformed

    private void btnCstBrowseProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCstBrowseProductsActionPerformed
        // TODO add your handling code here:
        ShopPageCustomers shopPageCustomers = new ShopPageCustomers(loggedInCustomer, currentOrder);
        shopPageCustomers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCstBrowseProductsActionPerformed

    private void btnCstViewMyProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCstViewMyProductsActionPerformed
        CustomerOrders cstOrders = new CustomerOrders(loggedInCustomer, currentOrder);
        cstOrders.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCstViewMyProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CustomerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCstBrowseProducts;
    private javax.swing.JButton btnCstEditDetails;
    private javax.swing.JButton btnCstLogOut;
    private javax.swing.JButton btnCstUnregisterFromShop;
    private javax.swing.JButton btnCstViewMyProducts;
    private javax.swing.JLabel lblCustomerHome;
    private javax.swing.JLabel lblGreeting;
    // End of variables declaration//GEN-END:variables
}
