/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.Staff;

/**
 *
 * @author 30397446
 */
public class StaffHome extends javax.swing.JFrame {

    private Staff loggedInStaff;
    /**
     * Creates new form StaffHome
     */
    public StaffHome(Staff staff) {
        
        loggedInStaff = staff;
        initComponents();
        
        lblGreeting.setText(loggedInStaff.displayGreeting());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStfModifyProducs = new javax.swing.JButton();
        btnStfViewAllProducts = new javax.swing.JButton();
        btnStfLogOut = new javax.swing.JButton();
        lblStaffHome = new javax.swing.JLabel();
        lblGreeting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStfModifyProducs.setText("Modify Products");
        btnStfModifyProducs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStfModifyProducsActionPerformed(evt);
            }
        });

        btnStfViewAllProducts.setText("View All Orders");
        btnStfViewAllProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStfViewAllProductsActionPerformed(evt);
            }
        });

        btnStfLogOut.setText("Log Out");
        btnStfLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStfLogOutActionPerformed(evt);
            }
        });

        lblStaffHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStaffHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStaffHome.setText("STAFF HOME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStfLogOut)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblStaffHome))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStfModifyProducs, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnStfViewAllProducts))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStaffHome)
                .addGap(18, 18, 18)
                .addComponent(btnStfModifyProducs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStfViewAllProducts)
                .addGap(94, 94, 94)
                .addComponent(btnStfLogOut)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStfLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStfLogOutActionPerformed
        StaffLogin staffLogin = new StaffLogin();
        staffLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStfLogOutActionPerformed

    private void btnStfModifyProducsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStfModifyProducsActionPerformed
        // TODO add your handling code here:
        ShopPageStaff shopPageStaff = new ShopPageStaff(loggedInStaff);
        shopPageStaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStfModifyProducsActionPerformed

    private void btnStfViewAllProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStfViewAllProductsActionPerformed
        StaffOrders staffOrders = new StaffOrders(loggedInStaff);
        staffOrders.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStfViewAllProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new StaffHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStfLogOut;
    private javax.swing.JButton btnStfModifyProducs;
    private javax.swing.JButton btnStfViewAllProducts;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JLabel lblStaffHome;
    // End of variables declaration//GEN-END:variables
}
